Resources: 
  Assignment1PrivateEC2EUWest1a:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: eu-west-1a
      ImageId: ami-0ee415e1b8b71305f
      InstanceType: !Ref InstanceTypeParameter 
      SecurityGroupIds:
        - sg-0060210a3d04512d9
      SecurityGroups:
        - instances

Outputs:
  Assignment1PrivateEC2EUWest1a:
    Value: !Ref 'Assignment1PrivateEC2EUWest1a'
    Description: Assignment1 Private EC2 Instance

Parameters:
  InstanceTypeParameter:
    Description: "Enter t2.nano or t2.micro. The default is set as t2.micro."
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
    ConstraintDescription: "Only t2.nano or t2.micro are permitted."

